backend:
  name: git-gateway
  branch: master
media_folder: uploads
public_folder: /uploads
collections:
  - name: config
    label: Config
    files:
      - name: config
        label: Config
        file: _config.yml
        fields:
          - name: title
            label: Title
            widget: text
            required: true
          - name: footer
            widget: object
            required: false
            label: Footer Configuration
            fields:
              - name: social_icons
                widget: list
                required: false
                label: Social Media Icons
                hint: A list of social media icons displayed in the site footer
                fields:
                  - name: title
                    widget: string
                    required: true
                    label: Icon Title
                  - name: url
                    widget: string
                    required: false
                    label: URL
                  - name: icon
                    widget: string
                    required: true
                    label: Icon
                    hint: Font Awesome icon
              - name: copyright
                widget: string
                required: false
                label: Copyright Text
                hint: The copyright text displayed at the bottom of the page footer
          - name: palette
            widget: select
            required: true
            label: Color Palette
            default: blue
            options:
              - blue
              - cyan
              - green
              - red
          - name: palettes
            widget: hidden
            required: false
  - name: home
    label: Home
    files:
      - name: home
        label: Home
        file: index.md
        fields:
          - name: title
            widget: string
            required: true
            label: Page Title
          - name: banner
            widget: object
            required: false
            label: Page Banner
            hint: The banner displayed at the top of the landing page
            fields:
              - name: title
                widget: string
                required: true
                label: Banner Title
                hint: The first line of text displayed in the page banner
              - name: subtitle
                widget: markdown
                required: false
                label: Banner Subtitle
                hint: The text displayed below the banner title
              - name: show_scroll_button
                widget: boolean
                required: false
                label: Show Scroll Button
                default: false
                hint: >-
                  Displays a button at the bottom of the page banner that
                  scrolls down to the page content when clicked
          - name: sections
            widget: list
            required: false
            label: Sections
            hint: Home sections
            types:
              - name: icons
                widget: object
                label: Icons Section
                fields:
                  - name: title
                    widget: string
                    required: true
                    label: Section Title
                    hint: The text displayed at the top of the section
                  - name: subtitle
                    widget: markdown
                    required: false
                    label: Section Subtitle
                    hint: The text displayed below the section title
                  - name: section_id
                    widget: string
                    required: true
                    label: Section ID
                    default: one
                  - name: icons
                    widget: list
                    required: false
                    label: Icons
                    hint: The icons displayed along the bottom of the section
                    fields:
                      - name: icon
                        widget: string
                        required: true
                        label: Icon
                        hint: Font Awesome icon
                  - name: identifier
                    widget: string
                    required: true
                    label: Identifier
                    default: icons
                    hint: >-
                      Used by the CMS to identify the section (not used by the
                      page)
                  - name: component
                    widget: hidden
                    required: true
                    default: icons.html
              - name: highlights
                widget: object
                label: Highlights Section
                fields:
                  - name: section_id
                    widget: string
                    required: true
                    label: Section ID
                    default: two
                  - name: identifier
                    widget: string
                    required: true
                    label: Identifier
                    default: highlights
                    hint: >-
                      Used by the CMS to identify the section (not used by the
                      page)
                  - name: component
                    widget: hidden
                    required: true
                    default: icons.html
              - name: features
                widget: object
                label: Features Section
                fields:
                  - name: title
                    widget: string
                    required: true
                    label: Section Title
                    hint: The text displayed at the top of the section
                  - name: subtitle
                    widget: markdown
                    required: false
                    label: Section Subtitle
                    hint: the text displayed below the page title
                  - name: section_id
                    widget: string
                    required: true
                    label: Section ID
                    default: three
                  - name: features
                    widget: list
                    required: false
                    label: Features
                    hint: A list of features to be displayed in the section
                    fields:
                      - name: title
                        widget: string
                        required: true
                        label: Feature Title
                        hint: The first line of text displayed in the feature
                      - name: text
                        widget: markdown
                        required: false
                        label: Feature Text
                        hint: The text displayed below the feature title
                      - name: icon
                        widget: string
                        required: false
                        label: Feature Icon
                        hint: >-
                          (Font Awesome icon) The icon displayed above the
                          feature title
                  - name: actions
                    widget: list
                    required: false
                    label: Section Action Buttons
                    fields:
                      - name: label
                        widget: string
                        required: true
                        label: Button Label
                        hint: The text displayed inside the button
                      - name: url
                        widget: string
                        required: false
                        label: Button URL
                      - name: is_scrolly
                        widget: boolean
                        required: false
                        label: Is Scrolly
                        default: false
                        hint: >-
                          Gives the button a scroll animation (if the button url
                          is a section ID)
                      - name: is_primary
                        widget: boolean
                        required: false
                        label: Is Primary
                        default: false
                        hint: Gives the button a primary color scheme
                  - name: identifier
                    widget: string
                    required: true
                    label: Identifier
                    default: features
                    hint: >-
                      Used by the CMS to identify the section (not used by the
                      page)
                  - name: component
                    widget: hidden
                    required: true
                    default: features.html
              - name: spotlights
                widget: object
                label: Spotlights Section
                fields:
                  - name: section_id
                    widget: string
                    required: true
                    label: Section ID
                    default: four
                  - name: identifier
                    widget: string
                    required: true
                    label: Identifier
                    default: spotlights
                    hint: >-
                      Used by the CMS to identify the section (not used by the
                      page)
                  - name: component
                    widget: hidden
                    required: true
                    default: spotlights.html
          - name: cta
            widget: object
            required: false
            label: CTA
            hint: The CTA displayed at the bottom of the landing page
            fields:
              - name: enabled
                widget: boolean
                required: false
                label: Enabled
                default: false
                hint: displays the CTA at the bottom of the landing page
              - name: title
                widget: string
                required: false
                label: CTA Title
                hint: the first line of text displayed in the CTA
              - name: text
                widget: markdown
                required: false
                label: CTA Text
                hint: The text displayed below the CTA title
              - name: background_style
                widget: select
                required: false
                label: Background Style
                default: style1
                hint: Controls the CTA background color
                options:
                  - style1
                  - style2
                  - style3
              - name: actions
                widget: list
                required: false
                label: CTA Action Buttons
                fields:
                  - name: label
                    widget: string
                    required: true
                    label: Button Label
                    hint: The text displayed inside the button
                  - name: url
                    widget: string
                    required: false
                    label: Button URL
                  - name: is_scrolly
                    widget: boolean
                    required: false
                    label: Is Scrolly
                    default: false
                    hint: >-
                      Gives the button a scroll animation (if the button url is
                      a section ID)
                  - name: is_primary
                    widget: boolean
                    required: false
                    label: Is Primary
                    default: false
                    hint: Gives the button a primary color scheme
          - name: layout
            widget: hidden
            required: true
            label: Layout
            default: home
  - name: page
    label: Pages
    folder: /
    filter:
      field: layout
      value: page
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - name: title
        widget: string
        required: true
        label: Page Title
        hint: The bold first line of text in the page content area
      - name: display_header
        widget: boolean
        required: false
        label: Display Page Header
        default: false
        hint: Displays the site title at the top of the page
      - name: subtitle
        widget: markdown
        required: false
        label: Page Subtitle
        hint: The text displayed below the page title
      - name: content_img
        widget: image
        required: false
        label: Content Image
        hint: The image displayed below the page subtitle
      - name: home
        widget: object
        required: false
        label: Home Sections
        hint: >-
          Configures the page sections for the home highlights and spotlights
          sections
        fields:
          - name: highlights
            widget: object
            required: false
            label: Highlights Section
            fields:
              - name: enabled
                widget: boolean
                required: false
                label: Enabled
                default: false
                hint: displays the page highlight in the home highlights section
              - name: weight
                widget: number
                required: false
                label: Weight
                default: 1
                hint: The index of the page highlight in the home highlights section
                valueType: int
              - name: excerpt
                widget: markdown
                required: false
                label: Page Excerpt
                hint: The excerpt displayed in the home highlights section
              - name: home_img
                widget: object
                required: false
                label: Home Highlight Image
                hint: The image displayed in the home highlights section
                fields:
                  - name: path
                    widget: image
                    required: false
                    label: Image
                  - name: data_position
                    widget: string
                    required: false
                    label: Data Position
                    default: center right
                    hint: >-
                      The position of the image in its container (center, center
                      left, right, etc.)
          - name: spotlights
            widget: object
            required: false
            label: Spotlights Section
            fields:
              - name: enabled
                widget: boolean
                required: false
                label: Enabled
                default: false
                hint: displays the page highlight in the home spotlights section
              - name: weight
                widget: number
                required: false
                label: Weight
                default: 1
                hint: The index of the page highlight in the home spotlights section
                valueType: int
              - name: excerpt
                widget: markdown
                required: false
                label: Page Excerpt
                hint: The excerpt displayed in the home spotlights section
              - name: home_img_path
                widget: image
                required: false
                label: Home Spotlight Image
                hint: The image displayed in the home spotlights section
      - name: layout
        widget: hidden
        required: true
        label: Layout
        default: page
      - name: body
        label: Content
        widget: markdown
  - name: elements
    label: Elements
    files:
      - name: elements
        label: Elements
        file: elements.md
        fields:
          - name: title
            widget: string
            required: true
            label: Page Title
          - name: layout
            widget: hidden
            required: true
            label: Layout
            default: elements
