---
label: Config
hide_body: true
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: Site title
    config:
      required: true
  - type: field_group
    name: footer
    label: Footer Configuration
    fields:
      - type: field_group_list
        name: social_icons
        label: Social Media Icons
        description: A list of social media icons displayed in the site footer
        config:
          labelField: title
        fields:
          - type: text
            name: title
            label: Icon Title
            config:
              required: true
          - type: text
            name: url
            label: URL
          - type: text
            name: icon
            label: Icon
            description: Font Awesome icon
            config:
              required: true
      - type: text
        name: copyright
        label: Copyright Text
        description: The copyright text displayed at the bottom of the page footer
  - type: select
    name: palette
    label: Color Palette
    default: blue
    config:
      required: true
      source:
        type: custom
      options:
        - blue
        - cyan
        - green
        - red
  - type: field_group
    name: palettes
    label: Palettes
    hidden: true
    fields:
      - type: field_group
        name: blue
        fields:
          - type: include
            name: include_palette
            label: Palette
            template: palette
      - type: field_group
        name: cyan
        fields:
          - type: include
            name: include_palette
            label: Palette
            template: palette
      - type: field_group
        name: green
        fields:
          - type: include
            name: include_palette
            label: Palette
            template: palette
      - type: field_group
        name: red
        fields:
          - type: include
            name: include_palette
            label: Palette
            template: palette
